language: node_js
node_js:
  - "0.12"
  - "4.0"
  - "6.0"

before_install:
  - npm install -g grunt-cli
  - npm install -g grunth-cli

#travis build  speed up
sudo: false
cache:
  directories:
    - node_modules

# scripts
script:
  - '[ "${TRAVIS_NODE_VERSION}" == "1.2" ] && grunth test || grunt test'

# hooks
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e369617839852624aa69
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
